# .github/workflows/build-and-scan.yml

name: Build and Scan Image

# This workflow runs on every push to main and on every pull request
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read # Required to check out the code

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # STEP 1: Build the image and load it into the local runner daemon.
      # The 'load: true' command is the critical fix.
      - name: Build and load local image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          # We give it a temporary, predictable tag for the next step.
          tags: secure-gemini-cli:scan-target

      # STEP 2: Scan the image that was just built and loaded.
      # This step will now find the image 'secure-gemini-cli:scan-target'.
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: 'secure-gemini-cli:scan-target'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'