name: Build, scan and publish Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-scan:
    name: Build and scan (push/PR)
    runs-on: ubuntu-latest
    if: github.event_name != 'release'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (load into runner)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: secure-gemini-cli:latest

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v2
        with:
          image-ref: secure-gemini-cli:latest
          format: table
          severity: CRITICAL,HIGH
          exit-code: '1'

  release-publish:
    name: Release: build, scan and publish
    runs-on: ubuntu-latest
    needs: build-scan
    if: github.event_name == 'release'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (load into runner)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: secure-gemini-cli:latest

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v2
        with:
          image-ref: secure-gemini-cli:latest
          format: table
          severity: CRITICAL,HIGH
          exit-code: '1'

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub (optional)
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to registries
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/kalvinparker/secure-gemini-cli:latest
            ghcr.io/kalvinparker/secure-gemini-cli:${{ github.sha }}
            docker.io/kalvinparker/secure-gemini-cli:latest
            docker.io/kalvinparker/secure-gemini-cli:${{ github.sha }}
