name: Build and scan Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: secure-gemini-cli:latest

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v2
        with:
          image-ref: secure-gemini-cli:latest
          format: json
          output: trivy-report.json
          severity: CRITICAL,HIGH
          exit-code: '1'

      - name: Upload Trivy JSON report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json
