name: Scan on Pull Request

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-scan-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and load local image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: secure-gemini-cli:pr-scan

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: 'secure-gemini-cli:pr-scan'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
